In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn

In [2]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, FunctionTransformer, OrdinalEncoder, RobustScaler, PowerTransformer, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import KNNImputer, SimpleImputer, IterativeImputer
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, HalvingGridSearchCV, cross_val_score, KFold, StratifiedKFold
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier, IsolationForest, AdaBoostClassifier, StackingClassifier, ExtraTreesClassifier
from sklearn.metrics import auc, roc_curve, balanced_accuracy_score, f1_score, roc_auc_score
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.svm import SVC, LinearSVC
from sklearn.neural_network import MLPClassifier
from sklearn.base import clone
from sklearn.feature_selection import SelectFromModel

from skopt import BayesSearchCV

from scipy.stats import mstats

from xgboost import XGBClassifier

from catboost import CatBoostClassifier, Pool

import optuna

import lightgbm as lgb

In [3]:
train = pd.read_csv("train.csv", index_col=0)
test = pd.read_csv("test.csv", index_col=0)

In [4]:
sklearn.set_config(transform_output="pandas")

In [5]:
train.head()

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,gender,stress_level,academic_work_impact,addicted_label
id,,,,,,,,,,,,,
0,24.0,NaN,1.83,1.59,2.11,7.46,122.0,38.0,8.63,Male,Medium,No,1
1,19.0,5.97,1.08,NaN,3.03,8.22,76.0,19.0,NaN,Female,Medium,No,0
2,18.0,5.09,NaN,NaN,NaN,6.25,134.0,60.0,7.47,Female,Low,Yes,0
3,21.0,6.42,1.26,1.42,3.36,8.85,112.0,94.0,8.66,Other,Low,NaN,1
4,26.0,11.20,1.87,2.81,1.95,5.25,NaN,NaN,13.39,Female,Medium,No,1

In [6]:
train['addicted_label'].value_counts()

addicted_label
1    490474
0    200895
Name: count, dtype: int64

In [7]:
train.isnull().sum() / train.count()

age                        0.043670
daily_screen_time_hours    0.160960
social_media_hours         0.240404
gaming_hours               0.224642
work_study_hours           0.080516
sleep_hours                0.068760
notifications_per_day      0.108345
app_opens_per_day          0.132169
weekend_screen_time        0.193444
gender                     0.043836
stress_level               0.086681
academic_work_impact       0.068337
addicted_label             0.000000
dtype: float64

In [8]:
(pd.get_dummies(train, dtype=int, drop_first=True).corr() > .3)

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,addicted_label,gender_Male,gender_Other,stress_level_Low,stress_level_Medium,academic_work_impact_Yes
age,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
daily_screen_time_hours,False,True,True,True,True,False,False,False,True,True,False,False,False,False,False
social_media_hours,False,True,True,False,False,False,False,False,True,True,False,False,False,False,False
gaming_hours,False,True,False,True,False,False,False,False,True,False,False,False,False,False,False
work_study_hours,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False
sleep_hours,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
notifications_per_day,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
app_opens_per_day,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
weekend_screen_time,False,True,True,True,True,False,False,False,True,True,False,False,False,False,False
addicted_label,False,True,True,False,False,False,False,False,True,True,False,False,False,False,False
gender_Male,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
gender_Other,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
stress_level_Low,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
stress_level_Medium,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
academic_work_impact_Yes,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [9]:
num_cols = train.loc[:, lambda x : x.dtypes == 'float64'].columns.to_list()
ord_cols = ['stress_level']
nom_cols = ['gender', 'academic_work_impact']
cat_cols = ['gender', 'academic_work_impact', 'stress_level']

In [10]:
from sklearn.model_selection import train_test_split

X, y = train.drop(labels="addicted_label", axis=1), train["addicted_label"]

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=.3, random_state=42)

In [11]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

simple_train = pd.get_dummies(train_X, dtype=int).corr() > .3

vif = pd.DataFrame()
vif["feature"] = simple_train.columns

vif["vif"] = [variance_inflation_factor(simple_train.values, i) for i in range(len(simple_train.columns))]

c:\Users\Ryan\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

In [12]:
vif

                     feature       vif
0                        age  1.000000
1    daily_screen_time_hours       inf
2         social_media_hours  2.161765
3               gaming_hours  2.161765
4           work_study_hours  2.161765
5                sleep_hours  1.000000
6      notifications_per_day  1.000000
7          app_opens_per_day  1.000000
8        weekend_screen_time       inf
9              gender_Female  1.000000
10               gender_Male  1.000000
11              gender_Other  1.000000
12         stress_level_High  1.000000
13          stress_level_Low  1.000000
14       stress_level_Medium  1.000000
15   academic_work_impact_No  1.000000
16  academic_work_impact_Yes  1.000000

In [13]:
def categorical_handler(df):
    df_c = df.copy()

    for col in nom_cols:
        df_c[col] = df_c[col].astype(str).replace('nan', 'missing').astype('category')
    stress_map = {'Low':0, 'Medium':1, 'High':2}
    df_c['stress_level'] = df_c['stress_level'].map(stress_map).fillna(-1).astype(int)

    return df_c

In [14]:
categorical_handler(train_X)

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,gender,stress_level,academic_work_impact
id,,,,,,,,,,,,
412708,28.0,9.49,3.67,1.23,3.76,8.26,128.0,180.0,13.21,Other,2,No
218301,35.0,NaN,0.79,NaN,1.50,4.63,224.0,78.0,NaN,Other,0,No
488140,NaN,11.57,2.69,1.76,2.52,8.04,68.0,155.0,10.16,Female,0,No
371198,18.0,9.17,2.98,2.98,0.81,7.34,123.0,151.0,6.07,Other,1,Yes
329533,20.0,5.55,1.76,2.51,NaN,5.27,243.0,42.0,NaN,Female,2,No
...,...,...,...,...,...,...,...,...,...,...,...,...
259178,NaN,12.96,4.94,0.71,5.26,6.70,87.0,36.0,13.29,missing,2,No
365838,NaN,11.54,4.86,NaN,4.43,8.42,22.0,45.0,15.83,missing,2,Yes
131932,33.0,8.23,4.26,0.33,2.93,5.71,245.0,62.0,14.10,Other,2,Yes
671155,21.0,6.58,0.61,2.40,2.76,6.47,155.0,17.0,7.67,Other,1,missing
121958,33.0,NaN,4.32,NaN,2.82,5.38,233.0,157.0,NaN,Male,0,No

In [15]:
categorical_transformer = FunctionTransformer(categorical_handler, validate=False)

In [16]:
num_pipe = Pipeline(steps=[('imputer', SimpleImputer(strategy='median', add_indicator=True)), ('outlier', PowerTransformer())])
nominal_pipe = Pipeline(steps=[('ohe', OneHotEncoder(sparse_output=False, handle_unknown='ignore'))])
preprocessing = ColumnTransformer(transformers=[("num", num_pipe, num_cols),
                                                ("nom", nominal_pipe, nom_cols)],
                                                remainder='passthrough'
                                                 )

In [17]:
feature_selector = SelectFromModel(
    estimator=ExtraTreesClassifier(n_estimators=50, random_state=42),
    threshold='median'
)

In [18]:
def drop_features(estimator):
    feature_selector = SelectFromModel(
    estimator=estimator,
    threshold='median'
)
    p = Pipeline(steps=[('data_casting', categorical_transformer), ('preprocessing', preprocessing), ('drop', feature_selector)])
    p.fit(train_X, train_y)
    drop_step = p.named_steps['drop']
    return ColumnTransformer(transformers=[('keep', 'passthrough', drop_step.get_support().tolist())])

In [19]:
clf_pipe = Pipeline(steps=[('data_casting', categorical_transformer), ('preprocessing', preprocessing),('drop', 'passthrough'), ('model', 'passthrough')])

In [20]:
    
def CV_pruner(classifier, pipe, trial):
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = [] 
    
    for fold, (train_idx, val_idx) in enumerate(cv.split(train_X, train_y)):
        X_tr, X_val = train_X.iloc[train_idx], train_X.iloc[val_idx]
        y_tr, y_val = train_y.iloc[train_idx], train_y.iloc[val_idx]


        model = clone(classifier)
        temp_p = clone(pipe)
        temp_p.set_params(model=model)

        temp_p.fit(X_tr, y_tr)
    
        preds = temp_p.predict_proba(X_val)[:, 1]
        fold_score = roc_auc_score(y_val, preds)
        scores.append(fold_score)
            
        current_mean = np.mean(scores)
        trial.report(current_mean, step=fold)
            
        if trial.should_prune():
            raise optuna.TrialPruned()

    return np.mean(scores)

In [21]:
trial1_pipe = clone(clf_pipe)
pipe2_params = {
        'preprocessing__num__outlier__standardize':False
    }
trial1_pipe.set_params(**pipe2_params)

def objective1(trial):
    depth = trial.suggest_int('max_depth', 0, 50)
    params = {
        'max_depth':None if depth == 0 else depth,
        'max_leaf_nodes':trial.suggest_int('max_leaf_nodes', 2, 50),
        'min_samples_leaf':trial.suggest_int('min_samples_leaf', 2, 10),
    }
    classifier = HistGradientBoostingClassifier(random_state=42, categorical_features="from_dtype", early_stopping='auto', **params)

    return CV_pruner(classifier, trial1_pipe, trial)

In [22]:
study1 = optuna.create_study(
direction='maximize',
pruner=optuna.pruners.MedianPruner(n_warmup_steps=1)
)

study1.optimize(objective1, n_jobs=-1, n_trials=50)

[I 2026-08-30 15:32:20,255] A new study created in memory with name: no-name-8427e985-d283-4efe-af18-fd2f5680357d
[I 2026-08-30 15:35:34,826] Trial 19 finished with value: 0.931359745692142 and parameters: {'max_depth': 37, 'max_leaf_nodes': 4, 'min_samples_leaf': 6}. Best is trial 19 with value: 0.931359745692142.
[I 2026-08-30 15:35:36,232] Trial 15 finished with value: 0.9290296089752934 and parameters: {'max_depth': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 9}. Best is trial 19 with value: 0.931359745692142.
[I 2026-08-30 15:35:45,201] Trial 4 finished with value: 0.9217323596067768 and parameters: {'max_depth': 30, 'max_leaf_nodes': 2, 'min_samples_leaf': 6}. Best is trial 19 with value: 0.931359745692142.
[I 2026-08-30 15:36:01,548] Trial 0 finished with value: 0.9361494723063701 and parameters: {'max_depth': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.9361494723063701.
[I 2026-08-30 15:36:03,458] Trial 7 finished with value: 0.9290296089752934 and parameters: {'max_depth': 2, 'max_leaf_nodes': 25, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.9361494723063701.
[I 2026-08-30 15:36:45,870] Trial 13 finished with value: 0.9426016676365176 and parameters: {'max_depth': 24, 'max_leaf_nodes': 10, 'min_samples_leaf': 9}. Best is trial 13 with value: 0.9426016676365176.
[I 2026-08-30 15:37:01,619] Trial 23 pruned.
[I 2026-08-30 15:37:23,069] Trial 16 finished with value: 0.9459090480112644 and parameters: {'max_depth': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2}. Best is trial 16 with value: 0.9459090480112644.
[I 2026-08-30 15:37:47,987] Trial 1 finished with value: 0.9479636868061021 and parameters: {'max_depth': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 9}. Best is trial 1 with value: 0.9479636868061021.
[I 2026-08-30 15:37:59,412] Trial 6 finished with value: 0.9473131723251758 and parameters: {'max_depth': 24, 'max_leaf_nodes': 15, 'min_samples_leaf': 8}. Best is trial 1 with value: 0.9479636868061021.
[I 2026-08-30 15:38:16,073] Trial 20 pruned.
[I 2026-08-30 15:38:50,258] Trial 11 finished with value: 0.9477093098825197 and parameters: {'max_depth': 6, 'max_leaf_nodes': 33, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.9479636868061021.
[I 2026-08-30 15:38:54,366] Trial 2 finished with value: 0.9446448452698053 and parameters: {'max_depth': 5, 'max_leaf_nodes': 33, 'min_samples_leaf': 9}. Best is trial 1 with value: 0.9479636868061021.
[I 2026-08-30 15:39:15,206] Trial 12 finished with value: 0.9525167271075888 and parameters: {'max_depth': 30, 'max_leaf_nodes': 27, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.9525167271075888.
[I 2026-08-30 15:39:18,377] Trial 28 pruned.
[I 2026-08-30 15:39:18,535] Trial 8 finished with value: 0.9500846795000649 and parameters: {'max_depth': 7, 'max_leaf_nodes': 33, 'min_samples_leaf': 6}. Best is trial 12 with value: 0.9525167271075888.
[I 2026-08-30 15:39:23,338] Trial 10 finished with value: 0.9509507940896722 and parameters: {'max_depth': 8, 'max_leaf_nodes': 31, 'min_samples_leaf': 6}. Best is trial 12 with value: 0.9525167271075888.
[I 2026-08-30 15:39:58,738] Trial 3 finished with value: 0.9531838969860985 and parameters: {'max_depth': 21, 'max_leaf_nodes': 29, 'min_samples_leaf': 9}. Best is trial 3 with value: 0.9531838969860985.
[I 2026-08-30 15:40:27,324] Trial 9 finished with value: 0.9478691116617751 and parameters: {'max_depth': 6, 'max_leaf_nodes': 48, 'min_samples_leaf': 5}. Best is trial 3 with value: 0.9531838969860985.
[I 2026-08-30 15:40:55,965] Trial 24 finished with value: 0.9477266335758319 and parameters: {'max_depth': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 5}. Best is trial 3 with value: 0.9531838969860985.
[I 2026-08-30 15:41:10,659] Trial 14 finished with value: 0.9549179736615712 and parameters: {'max_depth': 26, 'max_leaf_nodes': 42, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.9549179736615712.
[I 2026-08-30 15:41:24,299] Trial 5 finished with value: 0.9550388286047387 and parameters: {'max_depth': 38, 'max_leaf_nodes': 38, 'min_samples_leaf': 9}. Best is trial 5 with value: 0.9550388286047387.
[I 2026-08-30 15:41:40,587] Trial 17 finished with value: 0.9555082763182892 and parameters: {'max_depth': 13, 'max_leaf_nodes': 46, 'min_samples_leaf': 10}. Best is trial 17 with value: 0.9555082763182892.
[I 2026-08-30 15:41:41,249] Trial 27 finished with value: 0.9494189152556951 and parameters: {'max_depth': 49, 'max_leaf_nodes': 19, 'min_samples_leaf': 8}. Best is trial 17 with value: 0.9555082763182892.
[I 2026-08-30 15:41:45,749] Trial 25 finished with value: 0.9503281862514988 and parameters: {'max_depth': 37, 'max_leaf_nodes': 21, 'min_samples_leaf': 3}. Best is trial 17 with value: 0.9555082763182892.
[I 2026-08-30 15:41:52,677] Trial 18 finished with value: 0.955782012179131 and parameters: {'max_depth': 17, 'max_leaf_nodes': 48, 'min_samples_leaf': 6}. Best is trial 18 with value: 0.955782012179131.
[I 2026-08-30 15:42:02,847] Trial 21 finished with value: 0.9530625189544363 and parameters: {'max_depth': 11, 'max_leaf_nodes': 33, 'min_samples_leaf': 6}. Best is trial 18 with value: 0.955782012179131.
[I 2026-08-30 15:43:56,273] Trial 22 finished with value: 0.9551769417565742 and parameters: {'max_depth': 14, 'max_leaf_nodes': 44, 'min_samples_leaf': 5}. Best is trial 18 with value: 0.955782012179131.
[I 2026-08-30 15:44:30,955] Trial 30 finished with value: 0.9557516531060205 and parameters: {'max_depth': 17, 'max_leaf_nodes': 47, 'min_samples_leaf': 7}. Best is trial 18 with value: 0.955782012179131.
[I 2026-08-30 15:44:51,077] Trial 26 finished with value: 0.9564790191137085 and parameters: {'max_depth': 39, 'max_leaf_nodes': 50, 'min_samples_leaf': 10}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:45:14,259] Trial 31 finished with value: 0.954617030520733 and parameters: {'max_depth': 15, 'max_leaf_nodes': 42, 'min_samples_leaf': 4}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:45:17,565] Trial 29 finished with value: 0.9547396001018071 and parameters: {'max_depth': 48, 'max_leaf_nodes': 44, 'min_samples_leaf': 2}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:45:57,789] Trial 33 finished with value: 0.954642333377075 and parameters: {'max_depth': 15, 'max_leaf_nodes': 47, 'min_samples_leaf': 2}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:46:02,083] Trial 32 finished with value: 0.9548003176707723 and parameters: {'max_depth': 14, 'max_leaf_nodes': 43, 'min_samples_leaf': 4}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:46:06,444] Trial 36 finished with value: 0.954642333377075 and parameters: {'max_depth': 15, 'max_leaf_nodes': 47, 'min_samples_leaf': 2}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:46:10,985] Trial 35 finished with value: 0.9553603927517106 and parameters: {'max_depth': 15, 'max_leaf_nodes': 48, 'min_samples_leaf': 2}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:46:14,159] Trial 34 finished with value: 0.9551885209053449 and parameters: {'max_depth': 14, 'max_leaf_nodes': 50, 'min_samples_leaf': 2}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:46:54,632] Trial 38 finished with value: 0.9548777360235325 and parameters: {'max_depth': 16, 'max_leaf_nodes': 42, 'min_samples_leaf': 2}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:46:57,711] Trial 40 finished with value: 0.9550387322787783 and parameters: {'max_depth': 19, 'max_leaf_nodes': 43, 'min_samples_leaf': 2}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:46:59,938] Trial 37 finished with value: 0.955599214922983 and parameters: {'max_depth': 16, 'max_leaf_nodes': 47, 'min_samples_leaf': 2}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:47:07,555] Trial 39 finished with value: 0.9551933047458123 and parameters: {'max_depth': 18, 'max_leaf_nodes': 43, 'min_samples_leaf': 2}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:47:10,091] Trial 43 finished with value: 0.9556016586208594 and parameters: {'max_depth': 40, 'max_leaf_nodes': 43, 'min_samples_leaf': 10}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:47:18,716] Trial 41 finished with value: 0.9557448987329173 and parameters: {'max_depth': 19, 'max_leaf_nodes': 43, 'min_samples_leaf': 10}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:47:20,236] Trial 42 finished with value: 0.9556016586208594 and parameters: {'max_depth': 41, 'max_leaf_nodes': 43, 'min_samples_leaf': 10}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:47:20,911] Trial 45 finished with value: 0.9555095965821583 and parameters: {'max_depth': 17, 'max_leaf_nodes': 40, 'min_samples_leaf': 10}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:47:21,355] Trial 46 finished with value: 0.9554425073830103 and parameters: {'max_depth': 40, 'max_leaf_nodes': 41, 'min_samples_leaf': 10}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:47:22,505] Trial 44 finished with value: 0.9560881622230454 and parameters: {'max_depth': 17, 'max_leaf_nodes': 44, 'min_samples_leaf': 10}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:47:37,878] Trial 48 finished with value: 0.9564692306564456 and parameters: {'max_depth': 17, 'max_leaf_nodes': 50, 'min_samples_leaf': 10}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:47:39,519] Trial 47 finished with value: 0.9553923341785765 and parameters: {'max_depth': 17, 'max_leaf_nodes': 50, 'min_samples_leaf': 4}. Best is trial 26 with value: 0.9564790191137085.
[I 2026-08-30 15:47:42,970] Trial 49 finished with value: 0.9560271454939688 and parameters: {'max_depth': 18, 'max_leaf_nodes': 50, 'min_samples_leaf': 7}. Best is trial 26 with value: 0.9564790191137085.

In [23]:
trial2_pipe = clone(clf_pipe)
pipe2_params = {
        'preprocessing':'passthrough',
    }
trial2_pipe.set_params(**pipe2_params)

def objective2(trial):
    params = {
        'max_depth':trial.suggest_int('max_depth', 0, 50),
        'learning_rate':trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'min_child_weight':trial.suggest_float('min_child_weight', 1, 10)
    }
    classifier = XGBClassifier(random_state=42, enable_categorical=True, n_jobs=-1, **params)

    return CV_pruner(classifier, trial2_pipe, trial)

In [24]:
study2 = optuna.create_study(
    direction='maximize',
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=1)
)
study2.optimize(objective2, n_trials=50)

[I 2026-08-30 15:47:42,996] A new study created in memory with name: no-name-23ee1b76-3be1-43a8-bbf2-56e7de708314

[I 2026-08-30 15:47:50,692] Trial 0 finished with value: 0.9539065892710529 and parameters: {'max_depth': 10, 'learning_rate': 0.0745510714779866, 'min_child_weight': 6.144630493107862}. Best is trial 0 with value: 0.9539065892710529.
[I 2026-08-30 15:47:58,522] Trial 1 finished with value: 0.9497380407727682 and parameters: {'max_depth': 10, 'learning_rate': 0.0538606141647778, 'min_child_weight': 4.4839940488973}. Best is trial 0 with value: 0.9539065892710529.
[I 2026-08-30 15:48:06,100] Trial 2 finished with value: 0.9596761092430771 and parameters: {'max_depth': 11, 'learning_rate': 0.16324307488309248, 'min_child_weight': 9.870922736335093}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:49:19,592] Trial 3 finished with value: 0.9445090452423134 and parameters: {'max_depth': 27, 'learning_rate': 0.03347064153237455, 'min_child_weight': 2.637577847341617}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:51:51,786] Trial 4 finished with value: 0.9431176899210609 and parameters: {'max_depth': 50, 'learning_rate': 0.025642661168983852, 'min_child_weight': 3.1365691261457322}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:51:53,427] Trial 5 pruned.
[I 2026-08-30 15:53:17,474] Trial 6 finished with value: 0.9536379145860483 and parameters: {'max_depth': 33, 'learning_rate': 0.07717175206660364, 'min_child_weight': 3.120101321617232}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:53:47,185] Trial 7 pruned.
[I 2026-08-30 15:53:54,457] Trial 8 pruned.
[I 2026-08-30 15:53:56,570] Trial 9 pruned.
[I 2026-08-30 15:54:27,935] Trial 10 finished with value: 0.9570264401104651 and parameters: {'max_depth': 47, 'learning_rate': 0.19839190443468765, 'min_child_weight': 9.66379317131084}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:54:46,552] Trial 11 finished with value: 0.9577054787514374 and parameters: {'max_depth': 23, 'learning_rate': 0.19826921243157125, 'min_child_weight': 9.787587995148463}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:55:02,426] Trial 12 finished with value: 0.9584482081757273 and parameters: {'max_depth': 20, 'learning_rate': 0.17690344717366624, 'min_child_weight': 9.887846361987076}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:55:18,429] Trial 13 finished with value: 0.9583623832812791 and parameters: {'max_depth': 18, 'learning_rate': 0.11982851607360108, 'min_child_weight': 8.523897009995526}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:55:34,043] Trial 14 finished with value: 0.9585397666807228 and parameters: {'max_depth': 18, 'learning_rate': 0.12867718478233992, 'min_child_weight': 8.796661381086869}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:55:35,448] Trial 15 pruned.
[I 2026-08-30 15:56:48,508] Trial 16 pruned.
[I 2026-08-30 15:56:53,369] Trial 17 pruned.
[I 2026-08-30 15:57:09,450] Trial 18 pruned.
[I 2026-08-30 15:57:36,895] Trial 19 finished with value: 0.9580675036305394 and parameters: {'max_depth': 28, 'learning_rate': 0.14735760016336155, 'min_child_weight': 8.950051683877062}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:57:57,350] Trial 20 pruned.
[I 2026-08-30 15:58:13,598] Trial 21 finished with value: 0.9585844883251411 and parameters: {'max_depth': 20, 'learning_rate': 0.1637553522276491, 'min_child_weight': 9.884771352132098}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:58:32,644] Trial 22 finished with value: 0.9584510761166228 and parameters: {'max_depth': 22, 'learning_rate': 0.14674085693495334, 'min_child_weight': 9.270924059918677}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:58:37,432] Trial 23 pruned.
[I 2026-08-30 15:58:59,292] Trial 24 finished with value: 0.9582899094974128 and parameters: {'max_depth': 25, 'learning_rate': 0.1587557546727659, 'min_child_weight': 9.915539626490087}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:59:05,474] Trial 25 pruned.
[I 2026-08-30 15:59:12,419] Trial 26 finished with value: 0.9594903965559733 and parameters: {'max_depth': 10, 'learning_rate': 0.1555681107635143, 'min_child_weight': 8.144354651957482}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:59:19,354] Trial 27 finished with value: 0.9596671659769058 and parameters: {'max_depth': 10, 'learning_rate': 0.16735029606991073, 'min_child_weight': 8.01752560290323}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:59:21,909] Trial 28 pruned.
[I 2026-08-30 15:59:25,517] Trial 29 pruned.
[I 2026-08-30 15:59:27,446] Trial 30 pruned.
[I 2026-08-30 15:59:36,069] Trial 31 finished with value: 0.9596359669418606 and parameters: {'max_depth': 12, 'learning_rate': 0.16917121217429468, 'min_child_weight': 9.376958596691637}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:59:44,806] Trial 32 finished with value: 0.9595893485236229 and parameters: {'max_depth': 12, 'learning_rate': 0.17293080962654941, 'min_child_weight': 8.276710338601186}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 15:59:53,638] Trial 33 finished with value: 0.9594466354976104 and parameters: {'max_depth': 12, 'learning_rate': 0.19805569460010466, 'min_child_weight': 7.237504754915644}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 16:00:09,761] Trial 34 pruned.
[I 2026-08-30 16:00:11,728] Trial 35 pruned.
[I 2026-08-30 16:00:13,126] Trial 36 pruned.
[I 2026-08-30 16:00:22,055] Trial 37 finished with value: 0.9590137074388091 and parameters: {'max_depth': 12, 'learning_rate': 0.1302238543296036, 'min_child_weight': 9.332440037441732}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 16:00:28,017] Trial 38 pruned.
[I 2026-08-30 16:00:33,475] Trial 39 finished with value: 0.9588648786002697 and parameters: {'max_depth': 8, 'learning_rate': 0.16686297236260503, 'min_child_weight': 7.656179271639644}. Best is trial 2 with value: 0.9596761092430771.
[I 2026-08-30 16:00:35,300] Trial 40 pruned.
[I 2026-08-30 16:00:42,234] Trial 41 finished with value: 0.9597241182990555 and parameters: {'max_depth': 10, 'learning_rate': 0.1671908697535087, 'min_child_weight': 8.163444922941284}. Best is trial 41 with value: 0.9597241182990555.
[I 2026-08-30 16:00:50,856] Trial 42 finished with value: 0.9598641524744593 and parameters: {'max_depth': 12, 'learning_rate': 0.18170954816340065, 'min_child_weight': 9.348187164586776}. Best is trial 42 with value: 0.9598641524744593.
[I 2026-08-30 16:00:52,480] Trial 43 pruned.
[I 2026-08-30 16:01:05,797] Trial 44 finished with value: 0.9587620017778384 and parameters: {'max_depth': 16, 'learning_rate': 0.14173854982424816, 'min_child_weight': 8.96732616367269}. Best is trial 42 with value: 0.9598641524744593.
[I 2026-08-30 16:01:12,831] Trial 45 finished with value: 0.9599826216648767 and parameters: {'max_depth': 10, 'learning_rate': 0.18125904873880852, 'min_child_weight': 9.431384479925416}. Best is trial 45 with value: 0.9599826216648767.
[I 2026-08-30 16:01:15,778] Trial 46 pruned.
[I 2026-08-30 16:01:17,148] Trial 47 pruned.
[I 2026-08-30 16:01:27,685] Trial 48 finished with value: 0.9593507980046455 and parameters: {'max_depth': 14, 'learning_rate': 0.18714690319368688, 'min_child_weight': 9.661539786777421}. Best is trial 45 with value: 0.9599826216648767.
[I 2026-08-30 16:01:35,568] Trial 49 pruned.

In [25]:
trial3_pipe = clone(clf_pipe)
pipe3_params = {
        'preprocessing':'passthrough',
    }
trial3_pipe.set_params(**pipe3_params)


def objective3(trial):
    params = {
        'max_depth':trial.suggest_int('max_depth', 4, 10),
        'learning_rate':trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'min_child_samples':trial.suggest_float('min_child_samples', 1, 10),
    }
    classifier = CatBoostClassifier(
        **params,
        cat_features=['gender', 'academic_work_impact'], 
        early_stopping_rounds=20,
        task_type='GPU',
        random_state=42,
        iterations=250,
        verbose=False
    )    

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = [] 
    
    for fold, (train_idx, val_idx) in enumerate(cv.split(train_X, train_y)):
        X_tr, X_val = train_X.iloc[train_idx], train_X.iloc[val_idx]
        y_tr, y_val = train_y.iloc[train_idx], train_y.iloc[val_idx]


        model = clone(classifier)
        temp_p = clone(trial3_pipe)

        X_tr_proc = temp_p.fit_transform(X_tr, y_tr)
        X_val_proc = temp_p.transform(X_val)

        model.fit(X_tr_proc, y_tr, eval_set=(X_val_proc, y_val))
    
        preds = model.predict_proba(X_val_proc)[:, 1]
        fold_score = roc_auc_score(y_val, preds)
        scores.append(fold_score)
            
        current_mean = np.mean(scores)
        trial.report(current_mean, step=fold)
            
        if trial.should_prune():
            raise optuna.TrialPruned()

    return np.mean(scores)

In [26]:
study3 = optuna.create_study(
    direction='maximize',
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=1)
)
study3.optimize(objective3, n_trials=50)

[I 2026-08-30 16:01:35,598] A new study created in memory with name: no-name-6364c3f1-e3ea-431c-9fe8-30b8716aae96
[I 2026-08-30 16:02:06,947] Trial 0 finished with value: 0.9459502024157744 and parameters: {'max_depth': 7, 'learning_rate': 0.050045091469182484, 'min_child_samples': 1.667362756301001}. Best is trial 0 with value: 0.9459502024157744.
[I 2026-08-30 16:03:27,918] Trial 1 finished with value: 0.9517991396949796 and parameters: {'max_depth': 10, 'learning_rate': 0.06137488573325068, 'min_child_samples': 2.1213468292373605}. Best is trial 1 with value: 0.9517991396949796.
[I 2026-08-30 16:03:54,111] Trial 2 finished with value: 0.9366414237121802 and parameters: {'max_depth': 6, 'learning_rate': 0.022198397314791417, 'min_child_samples': 9.2237759624896}. Best is trial 1 with value: 0.9517991396949796.
[I 2026-08-30 16:04:25,528] Trial 3 finished with value: 0.9441252122776577 and parameters: {'max_depth': 7, 'learning_rate': 0.04116416116565907, 'min_child_samples': 5.1701888091196375}. Best is trial 1 with value: 0.9517991396949796.
[I 2026-08-30 16:05:05,692] Trial 4 finished with value: 0.9573384612630272 and parameters: {'max_depth': 8, 'learning_rate': 0.21306658816394847, 'min_child_samples': 7.284201155330822}. Best is trial 4 with value: 0.9573384612630272.
[I 2026-08-30 16:06:00,325] Trial 5 finished with value: 0.9561815562824062 and parameters: {'max_depth': 9, 'learning_rate': 0.13920189117047407, 'min_child_samples': 4.36547209061686}. Best is trial 4 with value: 0.9573384612630272.
[I 2026-08-30 16:06:41,641] Trial 6 finished with value: 0.9534275672344936 and parameters: {'max_depth': 8, 'learning_rate': 0.09788187216461523, 'min_child_samples': 7.894944279486034}. Best is trial 4 with value: 0.9573384612630272.
[I 2026-08-30 16:06:50,209] Trial 7 pruned.
[I 2026-08-30 16:07:15,897] Trial 8 finished with value: 0.9570039467891224 and parameters: {'max_depth': 6, 'learning_rate': 0.2902534684261595, 'min_child_samples': 7.756666272545683}. Best is trial 4 with value: 0.9573384612630272.
[I 2026-08-30 16:07:48,559] Trial 9 pruned.
[I 2026-08-30 16:07:55,931] Trial 10 pruned.
[I 2026-08-30 16:08:21,623] Trial 11 finished with value: 0.9570853057582458 and parameters: {'max_depth': 6, 'learning_rate': 0.2913718505283927, 'min_child_samples': 6.014575244822108}. Best is trial 4 with value: 0.9573384612630272.
[I 2026-08-30 16:09:01,474] Trial 12 finished with value: 0.9562538503023117 and parameters: {'max_depth': 8, 'learning_rate': 0.15964399667154097, 'min_child_samples': 5.794298130285174}. Best is trial 4 with value: 0.9573384612630272.
[I 2026-08-30 16:09:08,669] Trial 13 pruned.
[I 2026-08-30 16:09:35,086] Trial 14 finished with value: 0.9571691657819039 and parameters: {'max_depth': 6, 'learning_rate': 0.29691197532290564, 'min_child_samples': 6.052156616200336}. Best is trial 4 with value: 0.9573384612630272.
[I 2026-08-30 16:09:51,311] Trial 15 pruned.
[I 2026-08-30 16:10:04,010] Trial 16 pruned.
[I 2026-08-30 16:10:58,146] Trial 17 finished with value: 0.9571307164175422 and parameters: {'max_depth': 9, 'learning_rate': 0.20136507483524482, 'min_child_samples': 8.934998527534415}. Best is trial 4 with value: 0.9573384612630272.
[I 2026-08-30 16:11:06,921] Trial 18 pruned.
[I 2026-08-30 16:11:15,720] Trial 19 pruned.
[I 2026-08-30 16:11:37,574] Trial 20 pruned.
[I 2026-08-30 16:12:32,770] Trial 21 finished with value: 0.9573148603267094 and parameters: {'max_depth': 9, 'learning_rate': 0.20751993722448595, 'min_child_samples': 8.905818656972231}. Best is trial 4 with value: 0.9573384612630272.
[I 2026-08-30 16:13:29,452] Trial 22 finished with value: 0.9573322070366771 and parameters: {'max_depth': 9, 'learning_rate': 0.29703187404222636, 'min_child_samples': 8.856397897743985}. Best is trial 4 with value: 0.9573384612630272.
[I 2026-08-30 16:14:24,871] Trial 23 finished with value: 0.9573457337777411 and parameters: {'max_depth': 9, 'learning_rate': 0.20418800837155246, 'min_child_samples': 8.822405302327146}. Best is trial 23 with value: 0.9573457337777411.
[I 2026-08-30 16:14:57,321] Trial 24 pruned.
[I 2026-08-30 16:15:13,455] Trial 25 pruned.
[I 2026-08-30 16:16:09,430] Trial 26 finished with value: 0.9573720755896753 and parameters: {'max_depth': 9, 'learning_rate': 0.2421564199759535, 'min_child_samples': 8.281507050857137}. Best is trial 26 with value: 0.9573720755896753.
[I 2026-08-30 16:16:49,203] Trial 27 finished with value: 0.9573758111416548 and parameters: {'max_depth': 8, 'learning_rate': 0.21992582448985865, 'min_child_samples': 7.072091644944454}. Best is trial 27 with value: 0.9573758111416548.
[I 2026-08-30 16:17:21,424] Trial 28 pruned.
[I 2026-08-30 16:17:34,081] Trial 29 pruned.
[I 2026-08-30 16:18:29,200] Trial 30 finished with value: 0.9574173023180116 and parameters: {'max_depth': 9, 'learning_rate': 0.2475760275203986, 'min_child_samples': 9.502143142533349}. Best is trial 30 with value: 0.9574173023180116.
[I 2026-08-30 16:19:24,144] Trial 31 finished with value: 0.9573852200919195 and parameters: {'max_depth': 9, 'learning_rate': 0.242122757376441, 'min_child_samples': 9.469883048656257}. Best is trial 30 with value: 0.9574173023180116.
[I 2026-08-30 16:19:56,647] Trial 32 pruned.
[I 2026-08-30 16:20:51,153] Trial 33 finished with value: 0.9573582620211001 and parameters: {'max_depth': 9, 'learning_rate': 0.2378481217662136, 'min_child_samples': 9.540464024882757}. Best is trial 30 with value: 0.9574173023180116.
[I 2026-08-30 16:21:07,102] Trial 34 pruned.
[I 2026-08-30 16:21:23,522] Trial 35 pruned.
[I 2026-08-30 16:21:56,464] Trial 36 pruned.
[I 2026-08-30 16:22:18,333] Trial 37 pruned.
[I 2026-08-30 16:22:34,356] Trial 38 pruned.
[I 2026-08-30 16:22:46,867] Trial 39 pruned.
[I 2026-08-30 16:23:08,537] Trial 40 pruned.
[I 2026-08-30 16:24:03,859] Trial 41 finished with value: 0.957497861206526 and parameters: {'max_depth': 9, 'learning_rate': 0.25256503513986595, 'min_child_samples': 9.564324604515557}. Best is trial 41 with value: 0.957497861206526.
[I 2026-08-30 16:24:59,840] Trial 42 finished with value: 0.957367036916604 and parameters: {'max_depth': 9, 'learning_rate': 0.2597028672677132, 'min_child_samples': 9.288042480233932}. Best is trial 41 with value: 0.957497861206526.
[I 2026-08-30 16:25:32,919] Trial 43 pruned.
[I 2026-08-30 16:26:12,625] Trial 44 finished with value: 0.9576256028629162 and parameters: {'max_depth': 8, 'learning_rate': 0.25034193248374514, 'min_child_samples': 7.564030470186078}. Best is trial 44 with value: 0.9576256028629162.
[I 2026-08-30 16:26:28,719] Trial 45 pruned.
[I 2026-08-30 16:26:59,699] Trial 46 finished with value: 0.9574509818038912 and parameters: {'max_depth': 7, 'learning_rate': 0.2675267518105049, 'min_child_samples': 5.396353284238888}. Best is trial 44 with value: 0.9576256028629162.
[I 2026-08-30 16:27:31,620] Trial 47 finished with value: 0.9574103810722276 and parameters: {'max_depth': 7, 'learning_rate': 0.2681553127617416, 'min_child_samples': 5.283673142351519}. Best is trial 44 with value: 0.9576256028629162.
[I 2026-08-30 16:28:03,721] Trial 48 finished with value: 0.957438993510339 and parameters: {'max_depth': 7, 'learning_rate': 0.2704536866590745, 'min_child_samples': 5.420973094666234}. Best is trial 44 with value: 0.9576256028629162.
[I 2026-08-30 16:28:14,131] Trial 49 pruned.

In [27]:
trial4_pipe = clone(clf_pipe)
pipe4_params = {
        'preprocessing__num__outlier__standardize':False,
        'drop':drop_features(ExtraTreesClassifier(random_state=42, n_estimators=50))
    }
trial4_pipe.set_params(**pipe4_params)

def objective4(trial):
    depth = trial.suggest_int('max_depth', 0, 50)
    params = {
        'max_depth':None if depth == 0 else depth,
        'max_leaf_nodes':trial.suggest_int('max_leaf_nodes', 2, 50),
        'min_samples_split':trial.suggest_int('min_samples_split', 5, 10),
        'min_samples_leaf':trial.suggest_int('min_samples_leaf', 2, 10),
    }
    classifier = RandomForestClassifier(**params, n_jobs=-1, random_state=42)

    return CV_pruner(classifier, trial4_pipe, trial)

In [28]:
study4 = optuna.create_study(
    direction='maximize',
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=1)
)
study4.optimize(objective4, n_trials=50)

[I 2026-08-30 16:28:42,950] A new study created in memory with name: no-name-a7f6ee73-ebe9-4ee8-9998-ad711cf40382
[I 2026-08-30 16:29:23,121] Trial 0 finished with value: 0.9165977869303003 and parameters: {'max_depth': 37, 'max_leaf_nodes': 12, 'min_samples_split': 5, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.9165977869303003.
[I 2026-08-30 16:30:06,509] Trial 1 finished with value: 0.9260871708039483 and parameters: {'max_depth': 25, 'max_leaf_nodes': 39, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 1 with value: 0.9260871708039483.
[I 2026-08-30 16:30:49,454] Trial 2 finished with value: 0.9243599383599852 and parameters: {'max_depth': 38, 'max_leaf_nodes': 30, 'min_samples_split': 10, 'min_samples_leaf': 9}. Best is trial 1 with value: 0.9260871708039483.
[I 2026-08-30 16:31:32,526] Trial 3 finished with value: 0.9243599383599852 and parameters: {'max_depth': 46, 'max_leaf_nodes': 30, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 1 with value: 0.9260871708039483.
[I 2026-08-30 16:32:13,812] Trial 4 finished with value: 0.9208442724726821 and parameters: {'max_depth': 19, 'max_leaf_nodes': 19, 'min_samples_split': 9, 'min_samples_leaf': 7}. Best is trial 1 with value: 0.9260871708039483.
[I 2026-08-30 16:32:57,027] Trial 5 finished with value: 0.925212287743477 and parameters: {'max_depth': 13, 'max_leaf_nodes': 34, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 1 with value: 0.9260871708039483.
[I 2026-08-30 16:33:13,725] Trial 6 pruned.
[I 2026-08-30 16:33:57,713] Trial 7 finished with value: 0.9272283773935607 and parameters: {'max_depth': 18, 'max_leaf_nodes': 48, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 7 with value: 0.9272283773935607.
[I 2026-08-30 16:34:14,784] Trial 8 pruned.
[I 2026-08-30 16:34:57,435] Trial 9 finished with value: 0.9243599383599852 and parameters: {'max_depth': 21, 'max_leaf_nodes': 30, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 7 with value: 0.9272283773935607.
[I 2026-08-30 16:35:09,262] Trial 10 pruned.
[I 2026-08-30 16:35:53,217] Trial 11 finished with value: 0.9272283773935607 and parameters: {'max_depth': 26, 'max_leaf_nodes': 48, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 7 with value: 0.9272283773935607.
[I 2026-08-30 16:36:37,271] Trial 12 finished with value: 0.9274220430841436 and parameters: {'max_depth': 31, 'max_leaf_nodes': 50, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:37:20,906] Trial 13 finished with value: 0.9266134410113631 and parameters: {'max_depth': 32, 'max_leaf_nodes': 43, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:38:04,707] Trial 14 finished with value: 0.9266134410113631 and parameters: {'max_depth': 50, 'max_leaf_nodes': 43, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:38:48,359] Trial 15 finished with value: 0.9264810760383583 and parameters: {'max_depth': 31, 'max_leaf_nodes': 42, 'min_samples_split': 9, 'min_samples_leaf': 7}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:39:32,264] Trial 16 finished with value: 0.9272283773935607 and parameters: {'max_depth': 19, 'max_leaf_nodes': 48, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:39:45,908] Trial 17 pruned.
[I 2026-08-30 16:40:03,450] Trial 18 pruned.
[I 2026-08-30 16:40:47,602] Trial 19 finished with value: 0.9274220430841436 and parameters: {'max_depth': 27, 'max_leaf_nodes': 50, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:41:31,522] Trial 20 finished with value: 0.9267596182951214 and parameters: {'max_depth': 33, 'max_leaf_nodes': 44, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:42:15,541] Trial 21 finished with value: 0.9274220430841436 and parameters: {'max_depth': 26, 'max_leaf_nodes': 50, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:42:59,612] Trial 22 finished with value: 0.9274220430841436 and parameters: {'max_depth': 26, 'max_leaf_nodes': 50, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:43:43,360] Trial 23 finished with value: 0.9270018673999548 and parameters: {'max_depth': 29, 'max_leaf_nodes': 46, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:44:00,829] Trial 24 pruned.
[I 2026-08-30 16:44:18,144] Trial 25 pruned.
[I 2026-08-30 16:45:01,856] Trial 26 finished with value: 0.9268946554350622 and parameters: {'max_depth': 30, 'max_leaf_nodes': 45, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:45:45,735] Trial 27 finished with value: 0.9274220430841436 and parameters: {'max_depth': 22, 'max_leaf_nodes': 50, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:46:03,187] Trial 28 pruned.
[I 2026-08-30 16:46:20,458] Trial 29 pruned.
[I 2026-08-30 16:47:04,304] Trial 30 finished with value: 0.9270018673999548 and parameters: {'max_depth': 27, 'max_leaf_nodes': 46, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:47:48,331] Trial 31 finished with value: 0.9274220430841436 and parameters: {'max_depth': 28, 'max_leaf_nodes': 50, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:48:32,129] Trial 32 finished with value: 0.9270018673999548 and parameters: {'max_depth': 23, 'max_leaf_nodes': 46, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:49:16,139] Trial 33 finished with value: 0.9274220430841436 and parameters: {'max_depth': 26, 'max_leaf_nodes': 50, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:49:33,526] Trial 34 pruned.
[I 2026-08-30 16:50:17,414] Trial 35 finished with value: 0.9271154047429471 and parameters: {'max_depth': 34, 'max_leaf_nodes': 47, 'min_samples_split': 6, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:51:01,441] Trial 36 finished with value: 0.9274220430841436 and parameters: {'max_depth': 16, 'max_leaf_nodes': 50, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:51:18,862] Trial 37 pruned.
[I 2026-08-30 16:51:34,628] Trial 38 pruned.
[I 2026-08-30 16:51:52,117] Trial 39 pruned.
[I 2026-08-30 16:52:09,480] Trial 40 pruned.
[I 2026-08-30 16:52:53,451] Trial 41 finished with value: 0.9272283773935607 and parameters: {'max_depth': 22, 'max_leaf_nodes': 48, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:53:37,450] Trial 42 finished with value: 0.9274220430841436 and parameters: {'max_depth': 16, 'max_leaf_nodes': 50, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:54:21,332] Trial 43 finished with value: 0.9271154047429471 and parameters: {'max_depth': 26, 'max_leaf_nodes': 47, 'min_samples_split': 8, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:54:38,820] Trial 44 pruned.
[I 2026-08-30 16:55:22,918] Trial 45 finished with value: 0.9274057554725486 and parameters: {'max_depth': 11, 'max_leaf_nodes': 50, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:56:07,034] Trial 46 finished with value: 0.9272283773935607 and parameters: {'max_depth': 32, 'max_leaf_nodes': 48, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:56:24,479] Trial 47 pruned.
[I 2026-08-30 16:57:08,358] Trial 48 finished with value: 0.9272283773935607 and parameters: {'max_depth': 25, 'max_leaf_nodes': 48, 'min_samples_split': 7, 'min_samples_leaf': 7}. Best is trial 12 with value: 0.9274220430841436.
[I 2026-08-30 16:57:24,982] Trial 49 pruned.

In [29]:
trial5_pipe = clone(clf_pipe)
pipe5_params = {
        'drop':drop_features(LogisticRegression(random_state=42))
    }
trial5_pipe.set_params(**pipe5_params)

def objective5(trial):
    params = {
        'C':trial.suggest_float('C', .0001, 100, log=True),
        'l1_ratio':trial.suggest_float('l1_ratio', 0, 1, step=.01),
    }
    classifier = LogisticRegression(random_state=42, **params, solver='saga')

    return CV_pruner(classifier, trial5_pipe, trial)

In [30]:
study5 = optuna.create_study(
    direction='maximize',
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=1)
)
study5.optimize(objective5, n_jobs=-1, n_trials=50)

[I 2026-08-30 16:57:31,032] A new study created in memory with name: no-name-6e2eba17-1927-4aa7-9cdf-aaeee387f36b
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-08-30 17:00:36,769] Trial 15 finished with value: 0.9129677178457205 and parameters: {'C': 0.00014930974046963122, 'l1_ratio': 0.75}. Best is trial 15 with value: 0.9129677178457205.
[I 2026-08-30 17:00:38,175] Trial 9 finished with value: 0.9123417919696291 and parameters: {'C': 0.014943838867170269, 'l1_ratio': 0.92}. Best is trial 15 with value: 0.9129677178457205.
[I 2026-08-30 17:00:38,192] Trial 14 finished with value: 0.9123341247973249 and parameters: {'C': 0.027809851311286663, 'l1_ratio': 0.55}. Best is trial 15 with value: 0.9129677178457205.
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-08-30 17:00:39,298] Trial 18 finished with value: 0.9123454174544822 and parameters: {'C': 0.012339133202540367, 'l1_ratio': 0.59}. Best is trial 15 with value: 0.9129677178457205.
[I 2026-08-30 17:00:39,313] Trial 13 finished with value: 0.9123850751846454 and parameters: {'C': 0.004094417425671324, 'l1_ratio': 0.46}. Best is trial 15 with value: 0.9129677178457205.
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-08-30 17:00:44,821] Trial 6 finished with value: 0.9124199539680985 and parameters: {'C': 0.002536972543326333, 'l1_ratio': 0.42}. Best is trial 15 with value: 0.9129677178457205.
[I 2026-08-30 17:00:45,134] Trial 3 finished with value: 0.9124943317047389 and parameters: {'C': 0.0013387843985132274, 'l1_ratio': 0.41000000000000003}. Best is trial 15 with value: 0.9129677178457205.
[I 2026-08-30 17:00:48,911] Trial 1 finished with value: 0.9124299396762965 and parameters: {'C': 0.002276217487286673, 'l1_ratio': 0.02}. Best is trial 15 with value: 0.9129677178457205.
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-08-30 17:00:59,249] Trial 0 pruned.
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
[I 2026-08-30 17:01:00,032] Trial 19 finished with value: 0.912328785280921 and parameters: {'C': 0.0677814807994031, 'l1_ratio': 0.68}. Best is trial 15 with value: 0.9129677178457205.
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2026-08-30 17:01:01,477] Trial 16 pruned.
[I 2026-08-30 17:01:01,499] Trial 4 pruned.
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2026-08-30 17:01:02,166] Trial 2 pruned.
[I 2026-08-30 17:01:02,526] Trial 11 pruned.
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2026-08-30 17:01:03,528] Trial 12 pruned.
[I 2026-08-30 17:01:03,648] Trial 5 pruned.
[I 2026-08-30 17:01:03,663] Trial 8 pruned.
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2026-08-30 17:01:04,971] Trial 10 pruned.
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1197: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

In [31]:
from sklearn.calibration import CalibratedClassifierCV

trial6_pipe = clone(clf_pipe)
pipe6_params = {
        'drop':drop_features(LogisticRegression(random_state=42))
    }
trial6_pipe.set_params(**pipe6_params)

def objective6(trial):
    params = {
        'penalty':trial.suggest_categorical('penalty', ['l1', 'l2']),
        'alpha':trial.suggest_float('alpha', 1e-6, 100, log=True),
        'tol':trial.suggest_float('tol', 1e-4, 1e-2, log=True),
    }
    classifier = CalibratedClassifierCV(SGDClassifier(**params, loss='hinge', random_state=42))

    return CV_pruner(classifier, trial6_pipe, trial)

In [32]:
study6 = optuna.create_study(
    direction='maximize',
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=1)
)
study6.optimize(objective6, n_jobs=-1, n_trials=50)

[I 2026-08-30 17:06:33,744] A new study created in memory with name: no-name-76a38cf9-12fa-4169-a40d-8261429f2412
[I 2026-08-30 17:10:09,297] Trial 7 finished with value: 0.5 and parameters: {'penalty': 'l1', 'alpha': 0.5489723105066525, 'tol': 0.0006716466329145957}. Best is trial 7 with value: 0.5.
[I 2026-08-30 17:10:11,253] Trial 10 finished with value: 0.906757420875571 and parameters: {'penalty': 'l2', 'alpha': 0.6565722843020535, 'tol': 0.0003990722261810334}. Best is trial 10 with value: 0.906757420875571.
[I 2026-08-30 17:10:13,350] Trial 18 finished with value: 0.9113790134691296 and parameters: {'penalty': 'l1', 'alpha': 0.05556747236505547, 'tol': 0.0005525201595083202}. Best is trial 18 with value: 0.9113790134691296.
[I 2026-08-30 17:10:15,756] Trial 0 finished with value: 0.9120830614996173 and parameters: {'penalty': 'l1', 'alpha': 0.016340725454432166, 'tol': 0.003120221286754054}. Best is trial 0 with value: 0.9120830614996173.
[I 2026-08-30 17:10:16,080] Trial 2 finished with value: 0.9127974968337623 and parameters: {'penalty': 'l2', 'alpha': 0.013913261108669072, 'tol': 0.0002624037586596761}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:10:16,666] Trial 11 finished with value: 0.912686447127452 and parameters: {'penalty': 'l1', 'alpha': 0.0004650951192671626, 'tol': 0.004677963972505331}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:10:20,570] Trial 4 pruned.
[I 2026-08-30 17:10:22,730] Trial 8 pruned.
[I 2026-08-30 17:10:23,060] Trial 5 finished with value: 0.9127377096946473 and parameters: {'penalty': 'l1', 'alpha': 0.002547881172345205, 'tol': 0.0015613186447604934}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:10:25,341] Trial 3 pruned.
[I 2026-08-30 17:10:35,315] Trial 14 pruned.
[I 2026-08-30 17:10:41,773] Trial 6 pruned.
[I 2026-08-30 17:10:55,538] Trial 16 pruned.
[I 2026-08-30 17:10:56,341] Trial 17 finished with value: 0.9126636005822203 and parameters: {'penalty': 'l1', 'alpha': 0.00015643774727538455, 'tol': 0.0002867501906628403}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:10:58,425] Trial 13 pruned.
[I 2026-08-30 17:11:01,562] Trial 19 pruned.
[I 2026-08-30 17:11:30,796] Trial 20 pruned.
[I 2026-08-30 17:11:32,426] Trial 21 pruned.
[I 2026-08-30 17:11:33,723] Trial 22 pruned.
[I 2026-08-30 17:11:41,677] Trial 9 pruned.
[I 2026-08-30 17:11:45,333] Trial 15 pruned.
[I 2026-08-30 17:12:28,690] Trial 12 finished with value: 0.9125736181166527 and parameters: {'penalty': 'l2', 'alpha': 1.843647765595131e-05, 'tol': 0.000273445295517453}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:13:00,210] Trial 1 finished with value: 0.9125933863534934 and parameters: {'penalty': 'l2', 'alpha': 1.6959979153096614e-05, 'tol': 0.00021792602355877192}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:13:30,660] Trial 26 pruned.
[I 2026-08-30 17:13:42,069] Trial 33 pruned.
[I 2026-08-30 17:13:48,359] Trial 23 finished with value: 0.9126978520086132 and parameters: {'penalty': 'l2', 'alpha': 0.0007598693094619661, 'tol': 0.003659766073815513}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:14:02,037] Trial 24 finished with value: 0.9126700313516286 and parameters: {'penalty': 'l1', 'alpha': 0.004799028624375296, 'tol': 0.0004947663301520433}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:14:03,121] Trial 28 finished with value: 0.9124118126463024 and parameters: {'penalty': 'l2', 'alpha': 0.04175732005407724, 'tol': 0.0006297958990061361}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:14:11,708] Trial 25 pruned.
[I 2026-08-30 17:14:27,350] Trial 30 finished with value: 0.9127278258424468 and parameters: {'penalty': 'l2', 'alpha': 0.001302986012463706, 'tol': 0.0001401167666479308}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:14:32,730] Trial 31 finished with value: 0.9127645615553703 and parameters: {'penalty': 'l2', 'alpha': 0.002537688659472223, 'tol': 0.00010933062026617294}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:14:36,256] Trial 35 finished with value: 0.9127595417655867 and parameters: {'penalty': 'l2', 'alpha': 0.002670809534339288, 'tol': 0.0012881281393968217}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:14:36,337] Trial 34 finished with value: 0.9127708534601684 and parameters: {'penalty': 'l2', 'alpha': 0.0026298488594874193, 'tol': 0.00010163303907514863}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:14:42,351] Trial 32 finished with value: 0.9127518033951378 and parameters: {'penalty': 'l2', 'alpha': 0.0009651074033930977, 'tol': 0.0001018557023792291}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:15:06,415] Trial 37 finished with value: 0.9127405454410589 and parameters: {'penalty': 'l2', 'alpha': 0.0018263777836551524, 'tol': 0.0012347687469554387}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:15:06,770] Trial 38 finished with value: 0.9127174505705217 and parameters: {'penalty': 'l2', 'alpha': 0.001158951597741, 'tol': 0.0012173824447144885}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:15:07,012] Trial 36 finished with value: 0.9127112096509021 and parameters: {'penalty': 'l2', 'alpha': 0.0009562867184215721, 'tol': 0.0015235158793635223}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:15:15,885] Trial 40 finished with value: 0.9127133716937552 and parameters: {'penalty': 'l2', 'alpha': 0.0010914406101298958, 'tol': 0.0026350701624939907}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:15:17,023] Trial 39 finished with value: 0.9127447877059314 and parameters: {'penalty': 'l2', 'alpha': 0.0018823428100713298, 'tol': 0.00010319136502515359}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:15:37,109] Trial 41 finished with value: 0.9127129520473801 and parameters: {'penalty': 'l2', 'alpha': 0.001046620090893606, 'tol': 0.002467956266302486}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:15:40,456] Trial 27 finished with value: 0.9126098320496119 and parameters: {'penalty': 'l1', 'alpha': 2.5721462203763652e-05, 'tol': 0.0002534411261152486}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:15:47,384] Trial 29 pruned.
[I 2026-08-30 17:15:50,877] Trial 42 finished with value: 0.9126978218079044 and parameters: {'penalty': 'l2', 'alpha': 0.0007980294008384728, 'tol': 0.0029073249257751134}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:16:04,229] Trial 43 finished with value: 0.9127162418829569 and parameters: {'penalty': 'l2', 'alpha': 0.0011124073034683964, 'tol': 0.002649119779561791}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:16:06,951] Trial 45 finished with value: 0.9127451362821434 and parameters: {'penalty': 'l2', 'alpha': 0.001995080949122731, 'tol': 0.0025028189022370463}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:16:10,853] Trial 44 finished with value: 0.9127249961361507 and parameters: {'penalty': 'l1', 'alpha': 0.0009645588250887816, 'tol': 0.0029785780242908002}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:16:11,063] Trial 46 finished with value: 0.9127178528886896 and parameters: {'penalty': 'l2', 'alpha': 0.0011482893655540667, 'tol': 0.0020294832955265094}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:16:11,592] Trial 47 finished with value: 0.912727408279798 and parameters: {'penalty': 'l2', 'alpha': 0.0013616659058006612, 'tol': 0.0022384788027382937}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:16:12,292] Trial 48 finished with value: 0.9127371078464268 and parameters: {'penalty': 'l2', 'alpha': 0.0017470642836507218, 'tol': 0.0025136831716881503}. Best is trial 2 with value: 0.9127974968337623.
[I 2026-08-30 17:16:15,447] Trial 49 finished with value: 0.91277734867645 and parameters: {'penalty': 'l2', 'alpha': 0.0020347488770601973, 'tol': 0.00011940074170629185}. Best is trial 2 with value: 0.9127974968337623.

In [33]:
trial7_pipe = clone(clf_pipe)
pipe7_params = {
        'drop':drop_features(ExtraTreesClassifier(random_state=42, n_estimators=50))
    }
trial7_pipe.set_params(**pipe7_params)

def objective7(trial):
    params = {
        'hidden_layer_sizes':(trial.suggest_int('hidden_layer_sizes', 1, 200),),
        'activation':trial.suggest_categorical('activation', ['identity', 'logistic', 'tanh', 'relu']),
        'alpha':trial.suggest_float('alpha', .0001, 100, log=True),
    }
    classifier = MLPClassifier(**params, early_stopping=True, random_state=42)

    return CV_pruner(classifier, trial7_pipe, trial)

In [34]:
study7 = optuna.create_study(
    direction='maximize',
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=1)
)
study7.optimize(objective7, n_jobs=-1, n_trials=50)

[I 2026-08-30 17:16:44,541] A new study created in memory with name: no-name-71c054a2-a807-4e8c-b706-92e052f674ec
[I 2026-08-30 17:25:03,964] Trial 5 finished with value: 0.9045260216972588 and parameters: {'hidden_layer_sizes': 35, 'activation': 'relu', 'alpha': 74.30432777279925}. Best is trial 5 with value: 0.9045260216972588.
[I 2026-08-30 17:29:39,820] Trial 3 finished with value: 0.9167465921213095 and parameters: {'hidden_layer_sizes': 12, 'activation': 'logistic', 'alpha': 1.1852037758718754}. Best is trial 3 with value: 0.9167465921213095.
[I 2026-08-30 17:33:04,369] Trial 19 finished with value: 0.9033587030438632 and parameters: {'hidden_layer_sizes': 179, 'activation': 'logistic', 'alpha': 26.67817665227272}. Best is trial 3 with value: 0.9167465921213095.
[I 2026-08-30 17:37:56,349] Trial 13 finished with value: 0.9287451396672953 and parameters: {'hidden_layer_sizes': 26, 'activation': 'tanh', 'alpha': 0.6632374751492083}. Best is trial 13 with value: 0.9287451396672953.
[I 2026-08-30 17:40:12,407] Trial 14 finished with value: 0.914217920967871 and parameters: {'hidden_layer_sizes': 47, 'activation': 'identity', 'alpha': 0.058232035247872925}. Best is trial 13 with value: 0.9287451396672953.
[I 2026-08-30 17:42:36,150] Trial 2 pruned.
[I 2026-08-30 17:42:52,381] Trial 0 pruned.
[I 2026-08-30 17:43:26,033] Trial 18 pruned.
[I 2026-08-30 17:44:42,797] Trial 15 pruned.
[I 2026-08-30 17:45:27,218] Trial 8 finished with value: 0.9142696033402476 and parameters: {'hidden_layer_sizes': 75, 'activation': 'tanh', 'alpha': 6.842377943082627}. Best is trial 13 with value: 0.9287451396672953.
[I 2026-08-30 17:45:47,502] Trial 23 pruned.
[I 2026-08-30 17:45:50,850] Trial 20 finished with value: 0.9143849032395874 and parameters: {'hidden_layer_sizes': 171, 'activation': 'identity', 'alpha': 3.752230867360697}. Best is trial 13 with value: 0.9287451396672953.
[I 2026-08-30 17:46:05,173] Trial 7 finished with value: 0.9346233389770422 and parameters: {'hidden_layer_sizes': 133, 'activation': 'relu', 'alpha': 0.20163757833275692}. Best is trial 7 with value: 0.9346233389770422.
[I 2026-08-30 17:47:51,603] Trial 17 finished with value: 0.9360551628047711 and parameters: {'hidden_layer_sizes': 27, 'activation': 'logistic', 'alpha': 0.00286796430551182}. Best is trial 17 with value: 0.9360551628047711.
[I 2026-08-30 17:49:32,870] Trial 30 finished with value: 0.914358876403193 and parameters: {'hidden_layer_sizes': 1, 'activation': 'tanh', 'alpha': 0.18247715381705046}. Best is trial 17 with value: 0.9360551628047711.
[I 2026-08-30 17:50:09,821] Trial 24 pruned.
[I 2026-08-30 17:52:42,378] Trial 25 pruned.
[I 2026-08-30 17:54:26,160] Trial 22 pruned.
[I 2026-08-30 17:56:30,567] Trial 12 finished with value: 0.9376577141836808 and parameters: {'hidden_layer_sizes': 101, 'activation': 'relu', 'alpha': 0.0035608684132042755}. Best is trial 12 with value: 0.9376577141836808.
[I 2026-08-30 17:57:06,008] Trial 9 finished with value: 0.9374508288652263 and parameters: {'hidden_layer_sizes': 54, 'activation': 'relu', 'alpha': 0.00038538946599614334}. Best is trial 12 with value: 0.9376577141836808.
[I 2026-08-30 17:59:28,812] Trial 1 finished with value: 0.9379065990590505 and parameters: {'hidden_layer_sizes': 151, 'activation': 'relu', 'alpha': 0.0013612585606286546}. Best is trial 1 with value: 0.9379065990590505.
[I 2026-08-30 18:00:48,445] Trial 16 finished with value: 0.9369907519366174 and parameters: {'hidden_layer_sizes': 151, 'activation': 'tanh', 'alpha': 0.01607989242505799}. Best is trial 1 with value: 0.9379065990590505.
[I 2026-08-30 18:03:30,286] Trial 31 finished with value: 0.9330632979396631 and parameters: {'hidden_layer_sizes': 18, 'activation': 'tanh', 'alpha': 0.21781475906720735}. Best is trial 1 with value: 0.9379065990590505.
[I 2026-08-30 18:08:44,573] Trial 21 finished with value: 0.93704806230727 and parameters: {'hidden_layer_sizes': 42, 'activation': 'relu', 'alpha': 0.0003956066311635196}. Best is trial 1 with value: 0.9379065990590505.
[I 2026-08-30 18:16:56,579] Trial 26 finished with value: 0.9353597657459266 and parameters: {'hidden_layer_sizes': 54, 'activation': 'relu', 'alpha': 0.15042595112121857}. Best is trial 1 with value: 0.9379065990590505.
[I 2026-08-30 18:19:36,435] Trial 11 finished with value: 0.9371333338385863 and parameters: {'hidden_layer_sizes': 103, 'activation': 'tanh', 'alpha': 0.013797585284948807}. Best is trial 1 with value: 0.9379065990590505.
[I 2026-08-30 18:27:08,528] Trial 4 finished with value: 0.9349979069061642 and parameters: {'hidden_layer_sizes': 52, 'activation': 'logistic', 'alpha': 0.01891012245992315}. Best is trial 1 with value: 0.9379065990590505.
[I 2026-08-30 18:33:07,234] Trial 10 finished with value: 0.9372578855210938 and parameters: {'hidden_layer_sizes': 86, 'activation': 'logistic', 'alpha': 0.0005072406007733974}. Best is trial 1 with value: 0.9379065990590505.
[I 2026-08-30 18:38:29,237] Trial 32 finished with value: 0.9373693893791678 and parameters: {'hidden_layer_sizes': 105, 'activation': 'tanh', 'alpha': 0.00018939778413533251}. Best is trial 1 with value: 0.9379065990590505.
[I 2026-08-30 18:39:04,866] Trial 6 finished with value: 0.936721092072242 and parameters: {'hidden_layer_sizes': 184, 'activation': 'logistic', 'alpha': 0.003113596708688984}. Best is trial 1 with value: 0.9379065990590505.
[I 2026-08-30 18:40:01,657] Trial 35 finished with value: 0.9379453467594263 and parameters: {'hidden_layer_sizes': 116, 'activation': 'relu', 'alpha': 0.0011040968054442022}. Best is trial 35 with value: 0.9379453467594263.
[I 2026-08-30 18:40:07,287] Trial 34 finished with value: 0.9382234225089687 and parameters: {'hidden_layer_sizes': 120, 'activation': 'relu', 'alpha': 0.0016120364767329143}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:41:37,433] Trial 29 finished with value: 0.93773743574513 and parameters: {'hidden_layer_sizes': 124, 'activation': 'tanh', 'alpha': 0.00022520115793793244}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:42:00,892] Trial 28 finished with value: 0.9374588052011227 and parameters: {'hidden_layer_sizes': 137, 'activation': 'tanh', 'alpha': 0.0034662667476151564}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:43:09,279] Trial 36 finished with value: 0.9378413697871277 and parameters: {'hidden_layer_sizes': 114, 'activation': 'relu', 'alpha': 0.0012467753053901486}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:43:13,191] Trial 39 finished with value: 0.9380412203961337 and parameters: {'hidden_layer_sizes': 105, 'activation': 'relu', 'alpha': 0.00021907016927821008}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:43:15,382] Trial 40 finished with value: 0.9374312176975662 and parameters: {'hidden_layer_sizes': 108, 'activation': 'relu', 'alpha': 0.00016747636409823264}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:44:42,087] Trial 33 finished with value: 0.938104224440595 and parameters: {'hidden_layer_sizes': 106, 'activation': 'relu', 'alpha': 0.0005661699925061215}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:45:22,836] Trial 41 finished with value: 0.9379589163227884 and parameters: {'hidden_layer_sizes': 101, 'activation': 'relu', 'alpha': 0.00010588548273443106}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:46:32,625] Trial 38 finished with value: 0.9378702452173474 and parameters: {'hidden_layer_sizes': 102, 'activation': 'relu', 'alpha': 0.0010213169741762494}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:46:39,009] Trial 27 pruned.
[I 2026-08-30 18:47:42,349] Trial 37 finished with value: 0.9379965365635089 and parameters: {'hidden_layer_sizes': 130, 'activation': 'relu', 'alpha': 0.0012730822966400084}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:48:56,166] Trial 42 finished with value: 0.9379890188244655 and parameters: {'hidden_layer_sizes': 100, 'activation': 'relu', 'alpha': 0.00012649446350922007}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:49:16,276] Trial 43 finished with value: 0.9378821881837875 and parameters: {'hidden_layer_sizes': 96, 'activation': 'relu', 'alpha': 0.00013711091199989766}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:50:43,201] Trial 45 finished with value: 0.9379256824091222 and parameters: {'hidden_layer_sizes': 98, 'activation': 'relu', 'alpha': 0.00010685174476157421}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:52:10,959] Trial 44 finished with value: 0.9376851372040184 and parameters: {'hidden_layer_sizes': 98, 'activation': 'relu', 'alpha': 0.00010414590772907706}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:52:45,671] Trial 46 finished with value: 0.937879172723856 and parameters: {'hidden_layer_sizes': 95, 'activation': 'relu', 'alpha': 0.0001354690598681062}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:54:09,169] Trial 47 finished with value: 0.9378993543210538 and parameters: {'hidden_layer_sizes': 106, 'activation': 'relu', 'alpha': 0.00013916273425952047}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:54:33,905] Trial 49 finished with value: 0.9377704915639932 and parameters: {'hidden_layer_sizes': 112, 'activation': 'relu', 'alpha': 0.0016349763743658803}. Best is trial 34 with value: 0.9382234225089687.
[I 2026-08-30 18:57:10,964] Trial 48 finished with value: 0.9383939779613699 and parameters: {'hidden_layer_sizes': 198, 'activation': 'relu', 'alpha': 0.0020076931001219767}. Best is trial 48 with value: 0.9383939779613699.

In [35]:
trial8_pipe = clone(clf_pipe)
pipe8_params = {
        'preprocessing':'passthrough',
        'drop':'passthrough'
    }
trial8_pipe.set_params(**pipe8_params)

def objective8(trial):
    params = {
        'max_depth':trial.suggest_int('max_depth', 1, 15),
        'learning_rate':trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'num_leaves':trial.suggest_int('num_leaves', 10, 60)
    }
    classifier = lgb.LGBMClassifier(random_state=42, objective='binary', **params)
    
    return CV_pruner(classifier, trial8_pipe, trial)

In [36]:
study8 = optuna.create_study(
    direction='maximize',
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=1)
)
study8.optimize(objective8, n_jobs=-1, n_trials=50)

[I 2026-08-30 18:57:10,990] A new study created in memory with name: no-name-1c093848-6796-45ee-9e58-60d39afbd9f3
[I 2026-08-30 18:57:25,102] Trial 12 finished with value: 0.9124500218587114 and parameters: {'max_depth': 1, 'learning_rate': 0.01944347757565657, 'num_leaves': 46}. Best is trial 12 with value: 0.9124500218587114.
[I 2026-08-30 18:57:30,548] Trial 6 finished with value: 0.9209421003603703 and parameters: {'max_depth': 2, 'learning_rate': 0.013615923830404724, 'num_leaves': 22}. Best is trial 6 with value: 0.9209421003603703.
[I 2026-08-30 18:57:51,609] Trial 11 finished with value: 0.9396667988896382 and parameters: {'max_depth': 15, 'learning_rate': 0.06291179908751945, 'num_leaves': 12}. Best is trial 11 with value: 0.9396667988896382.
[I 2026-08-30 18:57:54,075] Trial 19 finished with value: 0.9312772687222889 and parameters: {'max_depth': 4, 'learning_rate': 0.03959592000900278, 'num_leaves': 44}. Best is trial 11 with value: 0.9396667988896382.
[I 2026-08-30 18:58:14,563] Trial 7 finished with value: 0.9314985560114263 and parameters: {'max_depth': 10, 'learning_rate': 0.0144671697112217, 'num_leaves': 23}. Best is trial 11 with value: 0.9396667988896382.
[I 2026-08-30 18:58:20,358] Trial 14 finished with value: 0.9481986167856062 and parameters: {'max_depth': 7, 'learning_rate': 0.0835592611630938, 'num_leaves': 29}. Best is trial 14 with value: 0.9481986167856062.
[I 2026-08-30 18:58:24,419] Trial 24 pruned.
[I 2026-08-30 18:58:25,006] Trial 2 finished with value: 0.9328304737565898 and parameters: {'max_depth': 14, 'learning_rate': 0.017033651342193114, 'num_leaves': 25}. Best is trial 14 with value: 0.9481986167856062.
[I 2026-08-30 18:58:26,007] Trial 3 finished with value: 0.9554555986994588 and parameters: {'max_depth': 13, 'learning_rate': 0.12316586135387028, 'num_leaves': 28}. Best is trial 3 with value: 0.9554555986994588.
[I 2026-08-30 18:58:27,641] Trial 8 finished with value: 0.9438946238871211 and parameters: {'max_depth': 10, 'learning_rate': 0.049190028321487334, 'num_leaves': 30}. Best is trial 3 with value: 0.9554555986994588.
[I 2026-08-30 18:58:36,977] Trial 0 finished with value: 0.9550193311208865 and parameters: {'max_depth': 9, 'learning_rate': 0.11528342444894796, 'num_leaves': 36}. Best is trial 3 with value: 0.9554555986994588.
[I 2026-08-30 18:58:37,748] Trial 20 finished with value: 0.9480070631952268 and parameters: {'max_depth': 12, 'learning_rate': 0.06082537110025427, 'num_leaves': 29}. Best is trial 3 with value: 0.9554555986994588.
[I 2026-08-30 18:58:38,368] Trial 22 pruned.
[I 2026-08-30 18:58:38,913] Trial 21 pruned.
[I 2026-08-30 18:58:39,268] Trial 1 pruned.
[I 2026-08-30 18:58:40,646] Trial 25 pruned.
[I 2026-08-30 18:58:43,438] Trial 4 pruned.
[I 2026-08-30 18:58:44,583] Trial 16 pruned.
[I 2026-08-30 18:58:47,902] Trial 10 finished with value: 0.9468514539881976 and parameters: {'max_depth': 8, 'learning_rate': 0.06281055449758999, 'num_leaves': 44}. Best is trial 3 with value: 0.9554555986994588.
[I 2026-08-30 18:58:48,858] Trial 17 finished with value: 0.9563686839855142 and parameters: {'max_depth': 6, 'learning_rate': 0.19787615916281334, 'num_leaves': 55}. Best is trial 17 with value: 0.9563686839855142.
[I 2026-08-30 18:58:50,237] Trial 13 pruned.
[I 2026-08-30 18:58:51,191] Trial 5 pruned.
[I 2026-08-30 18:58:53,967] Trial 23 pruned.
[I 2026-08-30 18:58:56,626] Trial 18 pruned.
[I 2026-08-30 18:58:57,189] Trial 15 finished with value: 0.9513189557553563 and parameters: {'max_depth': 10, 'learning_rate': 0.0719665132341479, 'num_leaves': 46}. Best is trial 17 with value: 0.9563686839855142.
[I 2026-08-30 18:58:59,939] Trial 9 finished with value: 0.9588339522784652 and parameters: {'max_depth': 13, 'learning_rate': 0.15121472269730682, 'num_leaves': 48}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:08,179] Trial 27 finished with value: 0.9529042498285463 and parameters: {'max_depth': 15, 'learning_rate': 0.1642114439782966, 'num_leaves': 15}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:10,665] Trial 44 pruned.
[I 2026-08-30 18:59:14,314] Trial 28 pruned.
[I 2026-08-30 18:59:24,259] Trial 37 finished with value: 0.9538265673240272 and parameters: {'max_depth': 11, 'learning_rate': 0.1818072580108895, 'num_leaves': 15}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:28,396] Trial 38 finished with value: 0.9537496973871551 and parameters: {'max_depth': 11, 'learning_rate': 0.18166693950904234, 'num_leaves': 15}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:35,864] Trial 43 finished with value: 0.9530181475697519 and parameters: {'max_depth': 5, 'learning_rate': 0.19805382824406792, 'num_leaves': 16}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:40,709] Trial 41 finished with value: 0.9521276402061062 and parameters: {'max_depth': 5, 'learning_rate': 0.17436327583450278, 'num_leaves': 60}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:40,756] Trial 26 finished with value: 0.9572358581465874 and parameters: {'max_depth': 14, 'learning_rate': 0.12162495026662111, 'num_leaves': 37}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:49,636] Trial 35 finished with value: 0.9586147959234201 and parameters: {'max_depth': 10, 'learning_rate': 0.1936376049703035, 'num_leaves': 38}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:49,851] Trial 34 finished with value: 0.9582255736999368 and parameters: {'max_depth': 9, 'learning_rate': 0.19787287339372284, 'num_leaves': 39}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:50,608] Trial 36 finished with value: 0.9580478108803308 and parameters: {'max_depth': 11, 'learning_rate': 0.18659583641432628, 'num_leaves': 37}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:53,915] Trial 31 finished with value: 0.958193335003236 and parameters: {'max_depth': 7, 'learning_rate': 0.19988740598656243, 'num_leaves': 56}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:55,225] Trial 33 finished with value: 0.9576751052484511 and parameters: {'max_depth': 7, 'learning_rate': 0.17866763302291394, 'num_leaves': 57}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:55,238] Trial 32 finished with value: 0.9568552953736684 and parameters: {'max_depth': 7, 'learning_rate': 0.160640945557507, 'num_leaves': 58}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 18:59:57,946] Trial 29 finished with value: 0.9584915797760148 and parameters: {'max_depth': 11, 'learning_rate': 0.18805779853569737, 'num_leaves': 60}. Best is trial 9 with value: 0.9588339522784652.
[I 2026-08-30 19:00:00,584] Trial 30 finished with value: 0.9593747480665111 and parameters: {'max_depth': 11, 'learning_rate': 0.18198150559137785, 'num_leaves': 59}. Best is trial 30 with value: 0.9593747480665111.
[I 2026-08-30 19:00:02,759] Trial 40 finished with value: 0.9589418240254901 and parameters: {'max_depth': 11, 'learning_rate': 0.1895936721612374, 'num_leaves': 58}. Best is trial 30 with value: 0.9593747480665111.
[I 2026-08-30 19:00:02,959] Trial 39 finished with value: 0.9590581099024182 and parameters: {'max_depth': 12, 'learning_rate': 0.18008417684087458, 'num_leaves': 58}. Best is trial 30 with value: 0.9593747480665111.
[I 2026-08-30 19:00:03,265] Trial 42 finished with value: 0.959163025828128 and parameters: {'max_depth': 10, 'learning_rate': 0.19685244961326503, 'num_leaves': 60}. Best is trial 30 with value: 0.9593747480665111.
[I 2026-08-30 19:00:04,465] Trial 46 finished with value: 0.9582595230755302 and parameters: {'max_depth': 12, 'learning_rate': 0.19998964523796794, 'num_leaves': 51}. Best is trial 30 with value: 0.9593747480665111.
[I 2026-08-30 19:00:04,777] Trial 45 finished with value: 0.9589205510107277 and parameters: {'max_depth': 12, 'learning_rate': 0.1972084188087633, 'num_leaves': 60}. Best is trial 30 with value: 0.9593747480665111.
[I 2026-08-30 19:00:05,154] Trial 47 finished with value: 0.9580336546702105 and parameters: {'max_depth': 12, 'learning_rate': 0.12171704013786765, 'num_leaves': 53}. Best is trial 30 with value: 0.9593747480665111.
[I 2026-08-30 19:00:05,161] Trial 48 finished with value: 0.9584871772580996 and parameters: {'max_depth': 13, 'learning_rate': 0.1953792238883367, 'num_leaves': 52}. Best is trial 30 with value: 0.9593747480665111.
[I 2026-08-30 19:00:05,964] Trial 49 finished with value: 0.9582185085379233 and parameters: {'max_depth': 13, 'learning_rate': 0.11978019791053193, 'num_leaves': 52}. Best is trial 30 with value: 0.9593747480665111.

In [38]:
estimators = [
        ('HGBC',trial1_pipe.set_params(model=HistGradientBoostingClassifier(random_state=42, **study1.best_params))),
        ('XGBC',trial2_pipe.set_params(model=XGBClassifier(random_state=42 ,enable_categorical=True, **study2.best_params))),
        ('CatBC',trial3_pipe.set_params(model=CatBoostClassifier(random_state=42,cat_features=nom_cols, early_stopping_rounds=20, verbose=False, **study3.best_params))),
        ('RF',trial4_pipe.set_params(model=RandomForestClassifier(random_state=42, **study4.best_params))),
        ('Log',trial5_pipe.set_params(model=LogisticRegression(random_state=42, solver='saga', **study5.best_params))),
        ('SVC',trial6_pipe.set_params(model=SGDClassifier(random_state=42, loss='hinge', **study6.best_params))),
        ('MLPCLass',trial7_pipe.set_params(model=MLPClassifier(random_state=42,**study7.best_params))),
        ('light',trial8_pipe.set_params(model=lgb.LGBMClassifier(random_state=42, objective='binary', **study8.best_params))),
]



clf = StackingClassifier(estimators, n_jobs=-1)

In [39]:
clf.fit(train_X, train_y)

StackingClassifier(estimators=[('HGBC',
                                Pipeline(steps=[('data_casting',
                                                 FunctionTransformer(func=<function categorical_handler at 0x0000020F670F9300>)),
                                                ('preprocessing',
                                                 ColumnTransformer(remainder='passthrough',
                                                                   transformers=[('num',
                                                                                  Pipeline(steps=[('imputer',
                                                                                                   SimpleImputer(add_indicator=True,
                                                                                                                 strategy='median')),
                                                                                                  ('outlier',
                                                                                                   PowerTransformer(standardize=Fa...
                                                               hidden_layer_sizes=198,
                                                               random_state=42))])),
                               ('light',
                                Pipeline(steps=[('data_casting',
                                                 FunctionTransformer(func=<function categorical_handler at 0x0000020F670F9300>)),
                                                ('preprocessing',
                                                 'passthrough'),
                                                ('drop', 'passthrough'),
                                                ('model',
                                                 LGBMClassifier(learning_rate=0.18198150559137785,
                                                                max_depth=11,
                                                                num_leaves=59,
                                                                objective='binary',
                                                                random_state=42))]))],
                   n_jobs=-1)

In [40]:
test_clf = clf.predict(test_X)

c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [41]:
roc_auc_score(y_true=test_y, y_score=test_clf)

0.8741344340989202

In [42]:
clf.score(test_X, test_y)

c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

0.9009551084561571

In [43]:
outf = pd.DataFrame({'id':test.index, 'addicted_label':clf.predict_proba(test)[:, 1]})

c:\Users\Ryan\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [44]:
outf.to_csv('AugustSubmission.csv', index=False)